kind: pipeline
name: default

steps:
  - name: 7.3-cli-alpine
    image: plugins/docker
    settings:
      username: maoxuner
      password:
        from_secret: docker_password
      context: core
      dockerfile: core/Dockerfile
      build_args:
        - PHP_TAG=7.3-cli-alpine
      repo: maoxuner/php
      tags: 7.3-cli-alpine

  - name: 7.3-fpm-alpine
    image: plugins/docker
    settings:
      username: maoxuner
      password:
        from_secret: docker_password
      context: core
      dockerfile: core/Dockerfile
      build_args:
        - PHP_TAG=7.3-fpm-alpine
      repo: maoxuner/php
      tags: 7.3-fpm-alpine

  - name: 5.6-apache
    image: plugins/docker
    settings:
      username: maoxuner
      password:
        from_secret: docker_password
      context: apache
      dockerfile: apache/Dockerfile
      build_args:
        - PHP_TAG=5.6-apache
      repo: maoxuner/php
      tags: 5.6-apache

  - name: customed
    image: plugins/docker
    settings:
      username: maoxuner
      password:
        from_secret: docker_password
      context: customed
      dockerfile: customed/Dockerfile
      build_args:
        - PHP_TAG=7.3-fpm-alpine
      repo: maoxuner/php
      tags: 7.3-customed

  - name: notify
    image: lddsb/drone-dingtalk-message
    settings:
      access_token:
        from_secret: dingtalk_token
      lang: zh_CN
      msg_type: text
      msg_at_all: false
    when:
      status:
        - success
        - failure
