kind: pipeline
name: default

clone:
  depth: 1
  skip_verify: true

steps:
  - name: 7.3-cli-alpine
    image: plugins/docker
    settings:
      context: core
      dockerfile: core/Dockerfile
      build_args:
        - PHP_TAG=7.3-cli-alpine
      tags: 7.3-cli-alpine
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker_password

  - name: 7.3-fpm-alpine
    image: plugins/docker
    settings:
      context: core
      dockerfile: core/Dockerfile
      build_args:
        - PHP_TAG=7.3-fpm-alpine
      tags: 7.3-fpm-alpine
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker_password

  - name: 5.6-apache
    image: plugins/docker
    settings:
      context: apache
      dockerfile: apache/Dockerfile
      build_args:
        - PHP_TAG=5.6-apache
      tags: 5.6-apache
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker_password

  - name: 7.3-composer
    image: plugins/docker
    settings:
      context: composer
      dockerfile: composer/Dockerfile
      build_args:
        - PHP_TAG=7.3-cli-alpine
        - COMPOSER_VERSION=1.8.5
        - INSTALLER_COMMIT=cb19f2aa3aeaa2006c0cd69a7ef011eb31463067
        - INSTALLER_HASH=48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5
      tags: 7.3-composer
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker_password

  - name: 7.3-customed
    image: plugins/docker
    settings:
      context: customed
      dockerfile: customed/Dockerfile
      build_args:
        - PHP_TAG=7.3-fpm-alpine
      tags: 7.3-customed
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker_password

  - name: notify
    image: lddsb/drone-dingtalk-message
    settings:
      access_token:
        from_secret: dingtalk_token
      lang: zh_CN
      msg_type: text
      msg_at_all: false
    when:
      status:
        - success
        - failure
