kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - promote

steps:
  - name: cli
    image: plugins/docker
    volumes:
      - name: docker-socket
        path: /run/docker.sock
    settings:
      mtu: 1450
      purge: false
      dockerfile: Dockerfile
      build_args:
        - PHP_TAG=${PHP_VERSION:-8.2.4}-cli-alpine
        - ROADRUNNER_TAG=${ROADRUNNER_VERSION:-2.12.3}
        - COMPOSER_TAG=${COMPOSER_VERSION:-2}
      tags:
        - ${PHP_VERSION:-8.2.4}-cli-alpine
        - latest
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker-password

  - name: fpm
    image: plugins/docker
    volumes:
      - name: docker-socket
        path: /run/docker.sock
    settings:
      mtu: 1450
      purge: false
      dockerfile: Dockerfile
      build_args:
        - PHP_TAG=${PHP_VERSION:-8.2.4}-fpm-alpine
        - ROADRUNNER_TAG=${ROADRUNNER_VERSION:-2.12.3}
        - COMPOSER_TAG=${COMPOSER_VERSION:-2}
      tags:
        - ${PHP_VERSION:-8.2.4}-fpm-alpine
      repo: maoxuner/php
      username: maoxuner
      password:
        from_secret: docker-password

  - name: notify
    image: lddsb/drone-dingtalk-message:1.2.8
    settings:
      success_token:
        from_secret: dingtalk-success-token
      success_secret:
        from_secret: dingtalk-success-secret
      failure_token:
        from_secret: dingtalk-failure-token
      failure_secret:
        from_secret: dingtalk-failure-secret
      lang: zh_CN
      msg_type: markdown
      msg_at_all: false
    commands:
      - set -e
      - |
        if [ $DRONE_BUILD_STATUS = "success" ]; then
            export PLUGIN_TOKEN=$PLUGIN_SUCCESS_TOKEN
            export PLUGIN_SECRET=$PLUGIN_SUCCESS_SECRET
        else
            export PLUGIN_TOKEN=$PLUGIN_FAILURE_TOKEN
            export PLUGIN_SECRET=$PLUGIN_FAILURE_SECRET
        fi
      - /bin/drone-dingtalk
    when:
      status:
        - success
        - failure

volumes:
  - name: docker-socket
    host:
      path: /run/docker.sock

---
kind: secret
name: docker-password
get:
  path: drone-docker-registry
  name: DOCKER_PASSWORD

---
kind: secret
name: dingtalk-success-token
get:
  path: drone-dingtalk-robot
  name: SUCCESS_TOKEN

---
kind: secret
name: dingtalk-success-secret
get:
  path: drone-dingtalk-robot
  name: SUCCESS_SECRET

---
kind: secret
name: dingtalk-failure-token
get:
  path: drone-dingtalk-robot
  name: FAILURE_TOKEN

---
kind: secret
name: dingtalk-failure-secret
get:
  path: drone-dingtalk-robot
  name: FAILURE_SECRET
