version: '1.0'
name: build
displayName: 构建镜像
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - master
variables:
  global:
    - PHP5
    - PHP7
    - PHP8
stages:
  - name: build
    displayName: 多版本构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: php8-cli-alpine
        displayName: php8 cli
        type: cert
        certificate: fe3222f0-cc1c-013d-d564-4292a631d605
        tag: maoxuner/php:${PHP8}-cli-alpine
        dockerfile: ./php8/Dockerfile
        context: ./php8
        artifacts: []
        isCache: true
        parameter:
          PHP_TAG: ${PHP8}-cli-alpine
        notify: []
        strategy:
          retry: '0'
