version: '1.0'
name: php8
displayName: PHP8
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
variables:
  PHP_TAG: 8.2.11
stages:
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker_cli
        displayName: cli
        type: cert
        certificate: b34f1b10-ba3e-013b-91d0-1ecb49bdcebb
        tag: maoxuner/php:${PHP_TAG}-cli-alpine
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter:
          PHP_TAG: ${PHP_TAG}-cli-alpine
        notify: []
        strategy:
          retry: '0'
      - step: build@docker
        name: build_docker_fpm
        displayName: fpm
        type: cert
        certificate: b34f1b10-ba3e-013b-91d0-1ecb49bdcebb
        tag: maoxuner/php:${PHP_TAG}-fpm-alpine
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter:
          PHP_TAG: ${PHP_TAG}-fpm-alpine
        notify: []
        strategy:
          retry: '0'
  - name: tags
    displayName: 标签
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker_latest
        displayName: latest
        type: cert
        certificate: b34f1b10-ba3e-013b-91d0-1ecb49bdcebb
        tag: maoxuner/php:latest
        dockerfile: ./Dockerfile
        context: ''
        artifacts: []
        isCache: false
        parameter:
          PHP_TAG: ${PHP_TAG}-cli-alpine
        notify:
          - certificate: 1bf0a710-303f-013c-0f4d-4afef757e4a0
            events:
              - success
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
          - certificate: 0a844880-303f-013c-ccf7-0e601ba24b3a
            events:
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: dingtalk
        strategy:
          retry: '0'
